### PR TITLE
Add a test to make sure console logging doesn't include colors

### PR DESCRIPTION
**Pull request by omajid**

### CODE REVIEW

**Comment by omajid** [comment]
cc @tmds

**Comment by tmds** [comment]
Upstream has a test for this also, so I don't think we need to check this.

The test looks good. Feel free to include it if you want.

**Comment by omajid** [comment]
> Upstream has a test for this also, so I don't think we need to check this.

Huh. And they still managed to regress this feature? :laughing:

**Comment by tmds** [comment]
The test got added with the fix.

**Pull request closed without merging**
