### PR TITLE
Add cgroup-limit test

### PR DESCRIPTION
**Pull request by tmds**
Fixes https://github.com/redhat-developer/dotnet-regular-tests/issues/108

### CODE REVIEW

**Comment by omajid** [comment]
CI is failing because this CI runs within a container and can't use `systemd-run`:

```
++ systemd-run -q --scope --user -p CPUQuota=100% -p MemoryLimit=100M bin/Debug/netcoreapp3.1/cgroup-limit
Failed to create bus connection: No such file or directory
```

For now, can you add a hack here? https://github.com/redhat-developer/dotnet-regular-tests/blob/bf7f0eabdb2f033f9cb9d87699c94b68f471fc77/.github/workflows/ci.yml#L54-L55

**Comment by tmds** [comment]
@omajid I've excluded the test from the github ci. The test passes on my Fedora 33. Do we have some automation that will run this new test on RHEL7 and RHEL8?

**Comment by omajid** [comment]
I don't think we have pre commit automation.

@RheaAyase do you have a way to run this pre commit? Or do we need to merge this before we can see how well it runs?

**Comment by tmds** [comment]
@omajid @RheaAyase I want to be sure that something runs this test on RHEL7/RHEL8 before it gets the opportunity to fail when we make a release. I'm fine if it runs when this is merged. The test itself is fine, since it works for me on Fedora 33.

**Comment by tmds** [comment]
From our irc discussion: CI will test this on RHEL8, and RHEL7. So I'll merge this.

**Pull request merged**
